//
//  SplashInteractor.swift
//  DubizzlesClassifieds
//
//  Created Shahzaib Iqbal Bhatti on 3/8/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SplashInteractor: SplashInteractorInputProtocol {

    weak var presenter: SplashInteractorOutputProtocol?
}
